"""Pass 2 — reconciliation / aggregation. PURE LOGIC, no LLM call.

Aggregates dated, confirmed, active observation grades for one sub-target and
proposes benchmark changes as candidates. Two invariants (design §4):

1. Gate-tight: reads only observations.status='active' whose source appointment
   is 'confirmed'. Drafts and invalidated facts never reach the count.
2. Idempotent against approved state: a change already reflected in the
   benchmark (benchmark_as_of advanced past the triggering obs) is not
   re-proposed; a duplicate pending candidate is not raised.

Thresholds are tuning parameters — settled against real reports during the 1d
data load. They live here as named constants for now.

The proposed new benchmark *text* (candidate.to_value) is generated by a Haiku
`summarize` callback (benchmark_update_prompt) injected by the caller, so this
module stays pure and unit-testable. Default stub leaves to_value NULL.
"""
from datetime import date

from src.db.writes import new_candidate, pending_benchmark_candidate_exists

# --- tuning thresholds (validate at the 1d data load) ---
PROGRESSION_MIN = 2      # >= N 'Above' since the benchmark -> progression warranted
REGRESSION_MIN = 2       # >= N 'Lower' since the benchmark -> regression warranted
ADDITION_MIN = 2         # >= N 'Gap' since the benchmark -> benchmark-extension warranted
REGRESSION_SPACING_DAYS = 90  # ...OR two 'Lower' spaced >= this far apart


def _days_between(d1: str, d2: str) -> int:
    return abs((date.fromisoformat(d1) - date.fromisoformat(d2)).days)


def confirmed_active_observations(conn, sub_target_id: str) -> list:
    """Gate-tight read: active obs on confirmed appointments, oldest first."""
    return conn.execute(
        """
        SELECT o.* FROM observations o
        JOIN appointments a ON o.source_encounter_id = a.id
        WHERE o.sub_target_id = ?
          AND o.status = 'active'
          AND a.status = 'confirmed'
        ORDER BY o.date
        """,
        (sub_target_id,),
    ).fetchall()


def aggregate(conn, sub_target_id: str) -> dict:
    """Return the supported-change picture for one sub-target (pure logic)."""
    st = conn.execute(
        "SELECT current_benchmark, benchmark_as_of, status FROM sub_targets WHERE id = ?",
        (sub_target_id,),
    ).fetchone()
    picture = {"sub_target_id": sub_target_id, "supported_changes": [],
               "counts": {}, "skipped": None}

    if st is None:
        picture["skipped"] = "no-such-sub-target"
        return picture
    as_of = st["benchmark_as_of"]
    if st["current_benchmark"] is None or as_of is None:
        # un-benchmarked (Adjacent-watch / blank Active) — no benchmark to advance;
        # Adjacent clustering / promotion is a separate weekly process.
        picture["skipped"] = "un-benchmarked"
        return picture

    obs = confirmed_active_observations(conn, sub_target_id)

    # only observations dated strictly after the current benchmark can drive a change;
    # earlier ones are already reflected. (Approval advances as_of, so this is what
    # makes re-running idempotent.)
    recent = [o for o in obs if o["date"] > as_of]
    above = [o for o in recent if o["assessment"] == "Above"]
    lower = [o for o in recent if o["assessment"] == "Lower"]
    gap = [o for o in recent if o["assessment"] == "Gap"]
    picture["counts"] = {"recent": len(recent), "Above": len(above),
                         "Lower": len(lower), "Gap": len(gap)}

    if len(above) >= PROGRESSION_MIN:
        picture["supported_changes"].append(
            {"kind": "Progression", "obs": above, "rule": f"{len(above)}x Above since {as_of}"})

    regression = len(lower) >= REGRESSION_MIN or (
        len(lower) >= 2 and _days_between(lower[0]["date"], lower[-1]["date"]) >= REGRESSION_SPACING_DAYS)
    if regression:
        picture["supported_changes"].append(
            {"kind": "Regression", "obs": lower, "rule": f"{len(lower)}x Lower since {as_of}"})

    if len(gap) >= ADDITION_MIN:
        picture["supported_changes"].append(
            {"kind": "Addition", "obs": gap, "rule": f"{len(gap)}x Gap since {as_of}"})

    return picture


def _default_summarize(kind, obs_rows, current_benchmark):
    """Stub used when no Haiku summarizer is injected (tests / pre-LLM). Returns
    (to_value, reason). Production passes a benchmark_update_prompt-backed callback."""
    notes = "; ".join(o["note"] for o in obs_rows if o["note"])[:300]
    return None, f"{kind} warranted: {len(obs_rows)} supporting observation(s). {notes}".strip()


def raise_candidates(conn, sub_target_id: str, picture: dict = None,
                     summarize=None, *, backfill=0, commit=True) -> list[str]:
    """Create benchmark-change candidates for the supported changes (idempotent).

    summarize(kind, obs_rows, current_benchmark) -> (to_value, reason). Defaults
    to a text stub so the module runs without an LLM.
    """
    if picture is None:
        picture = aggregate(conn, sub_target_id)
    if not picture["supported_changes"]:
        return []
    if pending_benchmark_candidate_exists(conn, sub_target_id):
        return []  # a benchmark change is already queued for review — don't pile on

    st = conn.execute(
        "SELECT current_benchmark FROM sub_targets WHERE id = ?", (sub_target_id,)
    ).fetchone()
    summarize = summarize or _default_summarize

    created = []
    for change in picture["supported_changes"]:
        to_value, reason = summarize(change["kind"], change["obs"], st["current_benchmark"])
        cid = new_candidate(
            conn, change_class="benchmark-change", origin="system",
            target_subtarget_id=sub_target_id,
            from_value=st["current_benchmark"], to_value=to_value, reason=reason,
            confidence="medium",
            source_observation_ids=[o["id"] for o in change["obs"]],
            triggering_rule=change["rule"], backfill=backfill,
        )
        created.append(cid)
        # one benchmark change reviewed at a time per sub-target (matches the guard above)
        break
    if commit:
        conn.commit()
    return created


def reconcile(conn, sub_target_id: str, summarize=None, *, backfill=0, commit=True) -> list[str]:
    """aggregate + raise_candidates for one sub-target."""
    return raise_candidates(conn, sub_target_id, aggregate(conn, sub_target_id),
                            summarize, backfill=backfill, commit=commit)
